# Generated by Django 3.2.18 on 2023-07-26 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20230726_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='file_upload',
            new_name='file',
        ),
    ]
